// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockExchange.Data.Context;

#nullable disable

namespace StockExchange.Data.Migrations
{
    [DbContext(typeof(StockExchangeDbContext))]
    [Migration("20260602115759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("StockExchange.Shared.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("StockExchange.Shared.Models.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_price");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sector");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Sector");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("StockExchange.Shared.Models.StockPriceDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("close_price");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("low_price");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("open_price");

                    b.Property<long>("StockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_id");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_date");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "TradingDate")
                        .IsUnique();

                    b.ToTable("stock_prices_day", (string)null);
                });

            modelBuilder.Entity("StockExchange.Shared.Models.StockPriceMinute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("close_price");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("low_price");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("open_price");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<long>("StockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_id");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "RecordedAt")
                        .IsUnique();

                    b.ToTable("stock_prices_minute", (string)null);
                });

            modelBuilder.Entity("StockExchange.Shared.Models.StockSimulation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AlgorithmType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("algorithm_type");

                    b.Property<decimal>("JumpProbability")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("jump_probability");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("max_price");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("min_price");

                    b.Property<long>("StockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_id");

                    b.Property<decimal>("TrendFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("trend_factor");

                    b.Property<decimal>("UpdateSpeed")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("update_speed");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Volatility")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("volatility");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("stock_simulations", (string)null);
                });

            modelBuilder.Entity("StockExchange.Shared.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StockExchange.Shared.Models.UserWatchlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("StockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_id");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId", "StockId")
                        .IsUnique();

                    b.ToTable("user_watchlists", (string)null);
                });

            modelBuilder.Entity("StockExchange.Shared.Models.RefreshToken", b =>
                {
                    b.HasOne("StockExchange.Shared.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockExchange.Shared.Models.StockPriceDay", b =>
                {
                    b.HasOne("StockExchange.Shared.Models.Stock", "Stock")
                        .WithMany("DayPrices")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockExchange.Shared.Models.StockPriceMinute", b =>
                {
                    b.HasOne("StockExchange.Shared.Models.Stock", "Stock")
                        .WithMany("MinutePrices")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockExchange.Shared.Models.StockSimulation", b =>
                {
                    b.HasOne("StockExchange.Shared.Models.Stock", "Stock")
                        .WithMany("Simulations")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockExchange.Shared.Models.UserWatchlist", b =>
                {
                    b.HasOne("StockExchange.Shared.Models.Stock", "Stock")
                        .WithMany("Watchlists")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockExchange.Shared.Models.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockExchange.Shared.Models.Stock", b =>
                {
                    b.Navigation("DayPrices");

                    b.Navigation("MinutePrices");

                    b.Navigation("Simulations");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("StockExchange.Shared.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
